### PR TITLE
Fix all pipeline templates

### PR DESCRIPTION
**Pull request by pradeepitm12**
Pipeline `deploy` step fails as it tries to deploy new application
deployment config is already created by `console +Add`

Instead deploy step should `rollout` the existing deployment

Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@pradeepitm12 We are pivoting away from `APPLICATION_NAME` and going with the pre-existing `APP_NAME` that we have in the UI for ease of implementation / support of this feature. @siamaksade asked me to log https://issues.redhat.com/browse/SRVKP-631

**Comment by pradeepitm12** [comment]
@andrewballantyne Thanks for the heads up. I will update the PR accordingly.

**Pull request merged**
