### PR TITLE
Merge v0.10.x to master

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add v0.10.x latest csv to master so that it can be refereed in future releases

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@hrishin 
> Wondering about deploy/resources/v0.10.1/addons/pipelines/buildah/buildah-build-deploy.yaml, otherwise looks good

you are right i have pushed a fix.
@pradeepitm12 could you validate the buildah pipeline

**Comment by hrishin** [comment]
/lgmt
/hold 

have we tetsed it @nikhil-thomas @pradeepitm12

**Comment by pradeepitm12** [comment]
> /lgtm
> /hold
> 
> have we tetsed it @nikhil-thomas @pradeepitm12 ?

@hrishin Test it, works fine.

**Pull request merged**
