### PR TITLE
add dashboard

### PR DESCRIPTION
**Pull request by akihikokuroda**
Adding the dashboard component to the operator

### CODE REVIEW

**Comment by sthaha** [comment]
@akihikokuroda I am sorry but this PR falls under the same category as explained in 
https://github.com/openshift/tektoncd-pipeline-operator/pull/46#issuecomment-504021247

> @akihikokuroda Thank for the PR while this patch adds value, do note that this repo contains operator specific to openshift and the dashboard so far isn't part of our openshift delivery, so we are sorry that we can't accept this particular PR.

> Our plan going forward is to present the operator upstream and to create tektoncd-operator which will form the basis of this operator and dashboard installation will certainly be a useful addon upstream. So please wait for upstream to approve off the operator and we can certainly make use of this PR upstream.


Would installing the dashboard as an `addon` once the https://github.com/openshift/tektoncd-pipeline-operator/pull/23 gets merged work? 

I will work on reviewing the `addon` patch to see if that can be merged soon.

**Comment by akihikokuroda** [comment]
OK.  I'll try using the addon for the dashboard in the meantime.  Thanks.

**Comment by akihikokuroda** [comment]
Yes, the dashboard work as an addon once the addon PR is merged.  Thanks.

**Comment by sthaha** [comment]
I will work on testing that patch and getting that merged next week. 
Thanks @akihikokuroda 🤗

**Comment by mnuttall** [comment]
Hi @sthaha please can I ask for some clarification about your comment above in which you wrote that 
> this PR falls under the same category as explained in https://github.com/openshift/tektoncd-pipeline-operator/pull/46#issuecomment-504021247

In that comment you wrote, 
> we are sorry that we can't accept this particular PR.

and referenced the proposal https://github.com/tektoncd/community/issues/26 to create an upstream project under Tekton. However you also wrote, 

> I will work on testing [ https://github.com/openshift/tektoncd-pipeline-operator/pull/23 ] and getting that merged next week

as a way to get PRs #23 and #24 merged into this repo. Please can you confirm whether PRs 23 and 24 will be accepted into https://github.com/openshift/tektoncd-pipeline-operator? Thank you very much in advance.

**Comment by sthaha** [comment]
@akihikokuroda sorry, the CI and the refactoring took this long. With #66 the CRD has changed a lot. Could you please rebase your changes on to the latest master? 

Thanks a lot for your patience.

**Comment by sthaha** [comment]
> Hi @sthaha please can I ask for some clarification about your comment above in which you wrote that
> 
> 
> as a way to get PRs #23 and #24 merged into this repo. Please can you confirm whether PRs 23 and 24 will be accepted into https://github.com/openshift/tektoncd-pipeline-operator? Thank you very much in advance.

@mnuttall, sorry the response took this long. I missed your comment somehow. 

 yes, I think the #23 is valuable but this needs to be rebased onto master as there are 2 significant changes to the operator 
1. the `install` crd which was `namespace` scope has been removed in favour of `config.operator.tekton.dev` CRD which is cluster-wide. 
2. we have added CI into the repo so that patches can now be tested before they are accepted. 

With regards to #24 , Openshift Pipelines operator does not ship `dashboard` yet (cc @siamaksade ) but the dashboard patch is useful in the upstream operator (which will be based on the current master).

**Comment by sthaha** [comment]
@akihikokuroda closing this PR since we have addons working upstream.

**Pull request closed without merging**
