### PR TITLE
Improve Operator Unistall information in FAQ

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

### CODE REVIEW

**Comment by chmouel** [comment]
Looks nice ! Can we add the caveat about GCS being (currently until vincent's fix is in) broken?

thanks

**Comment by nikhil-thomas** [comment]
> Looks nice ! Can we add the caveat about installing on GCS being (currently until @vdemeester 's fix is in) broken?
> 
> thanks

@chmouel it is already there, faq 3 ;)
are you saying we need to add more information there.

**Comment by chmouel** [comment]
@nikhil-thomas oopsie, tldr; 😂

**Comment by chmouel** [comment]
/lgtm
/approve

Thanks 👍🏼🔥

**Pull request merged**
