### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to openshift/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
/retest
as today the tests failed due to pod eviction
`reason BuildPodEvicted: Pod The node had condition: [DiskPressure]. `

**Note:** 
yesterday the e2e tests failed on 4.3 (`ci/prow/e2e`)
today it passed, but jobs on 4.4 failed (`ci/prow/variant-x-images`)

eventhough the update-to-head script tried to fetch the nightly midstream releaes.yaml again yesterday night, what it got is midstream release 0.12.1. This is same as yesterday. So there is no difference in payload.

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
