### PR TITLE
Add Triggers Release

### PR DESCRIPTION
**Pull request by khrm**
Add Triggers to operator alongside pipeline.

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@khrm 
just few linting errors

`./deploy/resources/v0.8.0/03-triggers/tektoncd-triggers-v0.1.0.yaml`
```
271:16    error    too many spaces after colon  (colons)
558:16    error    too many spaces after colon  (colons)
571:1     error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by khrm** [comment]
retest

**Pull request merged**
