### PR TITLE
Skip installation of upstream tasks for ppc64le and s390x

### PR DESCRIPTION
**Pull request by snehlatamohite**
Hi All,

Done changes as per requested in https://github.com/openshift/tektoncd-pipeline-operator/issues/478#issuecomment-741531695

Please review. 

Snehlata Mohite.

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@snehlatamohite The check in the `fetchCommuntiyResources` looks good.

But, needs 2 things
1. could you remove the check from here. https://github.com/openshift/tektoncd-pipeline-operator/blob/d38c5187be4752065e3f5cb23fb210643fd13a3d/pkg/controller/config/config_controller.go#L126

2. raise an addtional pr against 1.2.x branch with this exact patch

**Comment by snehlatamohite** [comment]
I have updated PR for following - 
could you remove the check from here.

tektoncd-pipeline-operator/pkg/controller/config/config_controller.go

Line 126 in d38c518

 if runtime1.GOARCH == "ppc64le" || runtime1.GOARCH == "s390x" {

**Comment by snehlatamohite** [comment]
I will raise an addtional pr against 1.2.x branch with this exact patch

**Comment by snehlatamohite** [comment]
@nikhil-thomas  - Please review PR for branch v1.2.x - https://github.com/openshift/tektoncd-pipeline-operator/pull/549

**Comment by snehlatamohite** [comment]
Ad discussed with Nikhil I have updated PR. There is a package conflict between
"k8s.io/apimachinery/pkg/runtime" and the standard library runtime and runtime1 is not a great naming choice so changed name to goruntime.

**Pull request merged**
