### PR TITLE
bump operator-sdk version to v0.14.1

### PR DESCRIPTION
**Pull request by pradeepitm12**
bump operator-sdk version to v0.14.1
    
    operator-sdk v0.14.1 requires kubernetes 1.16.2
    operator-sdk v0.10.1 to v0.14.1
    kubernetes v1.13.4 to v1.16.2
    
    pined manifestival to latest version
    
    updated test/helper WaitForDeploymentDeletion in accordence with
    k8s.io/apimachinery/pkg/apis/meta/v1
    
    docs update
    
    Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@pradeepitm12 thanks for this patch.

could you check whether v0.10.1 will work

To run tests we use both the operator-sdk cli and operator-sdk/pkg/test. At present the test depends on operator-sdk/pkg v0.10.1 (https://github.com/openshift/tektoncd-pipeline-operator/pull/142)

the expected formats of config files, static files might change with operator-sdk versions. So it is safe to match the operator-sdk cli version with the operator-sdk pkg version.

**Comment by nikhil-thomas** [comment]
or we can bump the pkg dependency to v14.0 (https://github.com/openshift/tektoncd-pipeline-operator/pull/191#pullrequestreview-344424907)

**Comment by pradeepitm12** [comment]
> or we can bump the pkg dependency to v14.0 ([#191 (review)](https://github.com/openshift/tektoncd-pipeline-operator/pull/191#pullrequestreview-344424907))

IMHO we should bump the pkg dependency to v14.0

**Comment by nikhil-thomas** [comment]
@pradeepitm12 there are some lint errors. could you fix those.

**Comment by nikhil-thomas** [comment]
@pradeepitm12 Thank you for your effort :+1

**Comment by nikhil-thomas** [comment]
@sthaha @vdemeester

**Comment by nikhil-thomas** [comment]
/hold
waiting for comments

**Pull request merged**
