### PR TITLE
Update Triggers to v0.3.1

### PR DESCRIPTION
**Pull request by khrm**

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@khrm 
```
297:16    error    too many spaces after colon  (colons)
  599:16    error    too many spaces after colon  (colons)
  612:1     error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by nikhil-thomas** [comment]
@khrm could you make one modification
instead of edition `deploy/resources/v0.10.1/addons/triggers/tektoncd-triggers-v0.2.1.yaml`
could you add it as `deploy/resources/devel/addons/triggers/tektoncd-triggers-v0.3.1.yaml`

**Comment by khrm** [comment]
@nikhil-thomas  I have added it as tektoncd-triggers-v0.3.1.yaml but git is assuming that I have just renamed it from tektoncd-triggers-v0.2.1.yaml

**Comment by nikhil-thomas** [comment]
> @nikhil-thomas I have added it as tektoncd-triggers-v0.3.1.yaml but git is assuming that I have just renamed it from tektoncd-triggers-v0.2.1.yaml

add in a new directory `resources/devel`
deploy/resources/`devel`/addons/triggers/tektoncd-triggers-v0.3.1.yaml

**Pull request merged**
