### PR TITLE
adds default value for version

### PR DESCRIPTION
**Pull request by pradeepitm12**
this adds default value for Major_Version or Minor_Version in the
pipeline

e.g.
      for dotnet-3 default value '1' which makes 1 as default minor
      version
      for nodejs default value '12' which makes 12 default major
      version

### CODE REVIEW

**Comment by pradeepitm12** [comment]
@karthikjeeyar request you to please take a look :smile:

**Comment by karthikjeeyar** [comment]
@pradeepitm12 Thank you for this PR. I have tested adding these default values in the templates (manually) and it works great.

**Comment by pradeepitm12** [comment]
> @pradeepitm12 Thank you for this PR. I have tested adding these default values in the templates (manually) and it works great. Changes looks good to me.

Thank you :smile:

**Review by vdemeester — APPROVED** [review]
/cc @nikhil-thomas 
@pradeepitm12 next step, porting this to tektoncd/operator :dancers:

**Comment by pradeepitm12** [comment]
@

> /cc @nikhil-thomas
> @pradeepitm12 next step, porting this to tektoncd/operator

Sure, I will take care of that.

**Comment by pradeepitm12** [comment]
/hold 
maybe we need to change the default minor_version for php from `2` to `2-ubi8`

**Comment by pradeepitm12** [comment]
> /hold
> maybe we need to change the default minor_version for php from `2` to `2-ubi8`

This could be a different story, this pr adds working default value for all the version params

**Pull request merged**
