### PR TITLE
Update e2e tests

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add right Registry Prefix, OPENSHIFT_REGISTRY_PREFIX=${IMAGE_FORMAT//:\$\{component\}/}

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
same fix has been added in @savitaashture 's pr https://github.com/openshift/tektoncd-pipeline-operator/pull/293
hence adding hold label
/hold

**Comment by vdemeester** [comment]
@nikhil-thomas needs a rebase ? (or close ?)

**Pull request closed without merging**
