### PR TITLE
CommunityResourceURLs: update according to catalog organization…

### PR DESCRIPTION
**Pull request by vdemeester**
- Track master branch
- Use versionned tasks

/cc @piyush-garg @nikhil-thomas @sthaha 

See https://issues.redhat.com/browse/SRVKP-825

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by piyush-garg** [comment]
i think we discussed to point to a specific commit sha

**Comment by vdemeester** [comment]
> i think we discussed to point to a specific commit sha

We should have the guarantee, with the `version` to not require to target a commit sha. We were also thinking of using a fork, but I wonder if we should do that now or as a follow-up (or not).

/cc @sthaha

**Comment by nikhil-thomas** [comment]
/lgtm
/approve

i think the version dir should be enough guarantee.
in addtion, not peggng to a commit will help us get updates/fixes in the tasks with the same version.

**Comment by piyush-garg** [comment]
I see, but for the release branch, we should point to specific sha. This is for master, so I think fine to be the latest.

/hold cancel

**Pull request merged**
