### PR TITLE
Automatically get latest version when installing oc tools

### PR DESCRIPTION
**Pull request by chmouel**
/cc @hrishin

### CODE REVIEW

**Comment by chmouel** [comment]
`latest` seems to point to `4.1.4` instead of `4.1.6` as available in the mirrors 🤷‍♂  maybe we can ping the openshift folks to check if that's a mistake?

**Comment by nikhil-thomas** [comment]
@chmouel Thanks :)

**Comment by hrishin** [comment]
@nikhil-thomas

**Pull request merged**
